(()=>{'use strict';const d=window.S2Guide,$=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function day(n){document.querySelectorAll('[data-day]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.day===String(n))));const rows=d.days.filter(x=>Number(x.day.split('／')[0])===n);$('dayContent').innerHTML=rows.map(x=>'<article class="panel"><h3>'+esc(x.day)+'</h3>'+Object.entries(x).filter(([k])=>k!=='day').map(([k,v])=>'<p><strong>'+({type:'證據分類',checkpoint:'本日重點',source:'來源',numbers:'數字與算術',failure_rule:'失敗時',warning:'限制',advanced_case:'進階案例'}[k]||k)+'：</strong>'+esc(v)+'</p>').join('')+'</article>').join('');}
document.querySelectorAll('[data-day]').forEach(b=>b.addEventListener('click',()=>day(Number(b.dataset.day))));day(1);
function route(){const x=d.routes[Number($('rosterRoute').value)];$('routeAdvice').innerHTML='<h3>'+esc(x.first)+'</h3><p>'+esc(x.alternative)+'</p><small>條件式編者建議；池開放跟本服進程。</small>';}$('rosterRoute').onchange=route;route();
function budget(){const a=Number($('budgetTotal').value),b=Number($('budgetReserve').value),p=Number($('pullPrice').value);$('budgetAdvice').textContent=[a,b].some(x=>!Number.isFinite(x)||x<0)||!Number.isFinite(p)||p<=0?'先填入有效預算與本服確認價格。':'可用 '+Math.max(0,a-b)+' 小判，最多 '+Math.floor(Math.max(0,a-b)/p)+' 抽。';}['budgetTotal','budgetReserve','pullPrice'].forEach(id=>$(id).oninput=budget);budget();
function canonical(q){let s=q.trim();for(const [a,b] of Object.entries(d.aliases))s=s.replaceAll(a,b);return s;}
function teams(){const q=canonical($('teamQuery').value),stage=$('teamStage').value;document.querySelectorAll('[data-stage]').forEach(c=>c.hidden=!(stage==='all'||stage===c.dataset.stage)||!c.textContent.includes(q));const n=[...document.querySelectorAll('[data-stage]')].filter(c=>!c.hidden).length;$('teamCount').textContent=n?'顯示 '+n+' / 11 隊':'沒有符合條件的隊伍，請調整搜尋或階段。';}$('teamQuery').oninput=teams;$('teamStage').onchange=teams;teams();
function index(){const q=canonical($('indexQuery').value);let count=0;document.querySelectorAll('.index-card').forEach(c=>{c.hidden=!c.textContent.includes(q);if(!c.hidden)count++;});$('indexCount').textContent='顯示 '+count+' / 136 位；只確認卡池收錄。';}$('indexQuery').oninput=index;index();
})();
