(function(root){'use strict';
const source='https://news.omg.com.tw/News/NewsContent?NewsID=11422';
const seeds=[['黑田官兵衛','如水',['輸出'],'治療與謀略狀態有互動，需核對目前觸發條件。'],['高橋紹運','豐後戰神',['輸出'],'洞察與最高屬性相關；增益依現行介面核對。'],['山縣昌景','武田之赤備',['輸出'],'會心互動的歷史介紹；社群曾討論調整，現行機制未核實。'],['前田慶次','天下御免',['輸出','控制'],'普攻後追加與控制；歷史介紹涉及大將條件。'],['里見義堯','仁者懷勇',['輸出','聯動'],'謀略傷害與友軍聯動，條件待核對。'],['大內義隆','末世道者',['輔助'],'支援智略最高友軍；需核對目標與屬性。'],['相馬盛胤','先陣鼓舞',['輔助'],'提升友軍自帶戰法發動的歷史介紹。'],['瑞溪院','諸行無常',['輔助'],'前期增傷，後期效果不同；時序待核對。']];
const roles=['輸出','治療','輔助','聯動','控制','防禦'];const evidence=['official','game-screen','community','unknown'];
function blank(kind='general'){return {id:'custom-'+Date.now()+'-'+Math.random().toString(36).slice(2,7),name:'',region:'TW',season:'S2',date:'',source:'',evidence:'unknown',note:'',owned:false,roles:[],...(kind==='general'?{innate:'',cost:null,level:null,strength:null,intellect:null,command:null,speed:null}:{level:null,copyLimit:null,exclusiveGroup:''})};}
function initial(){return {version:1,region:'TW',generals:seeds.map((s,i)=>({...blank(),id:'seed-'+i,name:s[0],innate:s[1],roles:s[2],note:s[3],evidence:'community',source,date:'2026-01-23',historical:true})),tactics:[],team:[null,null,null],equipped:[[],[],[]],cap:null,tacticCap:null,goal:'balanced',ruleEvidence:'unknown',duplicateRule:'unknown'};}
function validUrl(v){if(!v)return true;try{return ['https:','http:'].includes(new URL(v).protocol);}catch{return false}}
function numeric(v,max){return v===null||(typeof v==='number'&&Number.isFinite(v)&&v>=0&&v<=max);}
function validate(data){if(!data||typeof data!=='object'||Array.isArray(data))throw Error('備份必須為物件');if(data.version!==1)throw Error('不支援的備份版本');if(!['TW','HKMO'].includes(data.region))throw Error('地區格式錯誤');if(!Array.isArray(data.generals)||data.generals.length>500||!Array.isArray(data.tactics)||data.tactics.length>500)throw Error('資料庫格式錯誤或超過 500 筆');const ids=new Set();for(const [list,kind] of [[data.generals,'general'],[data.tactics,'tactic']])for(const g of list){if(!g||typeof g!=='object')throw Error('資料列錯誤');for(const [key,max] of [['id',100],['name',80],['season',30],['date',30],['source',1000],['note',3000]])if(typeof g[key]!=='string'||g[key].length>max||(key==='name'&&!g[key].trim()))throw Error('文字欄位格式錯誤：'+key);if(ids.has(g.id)||!g.id)throw Error('ID 重複或空白');ids.add(g.id);if(!['TW','HKMO'].includes(g.region)||!evidence.includes(g.evidence)||typeof g.owned!=='boolean'||!Array.isArray(g.roles)||g.roles.some(x=>!roles.includes(x))||!validUrl(g.source))throw Error('資料來源或角色格式錯誤');if(g.date&&!/^\d{4}-\d{2}-\d{2}$/.test(g.date))throw Error('日期格式錯誤');if(g.historical!==undefined&&typeof g.historical!=='boolean')throw Error('歷史標記錯誤');if(kind==='tactic'){if(g.copyLimit!==undefined&&(!numeric(g.copyLimit,50)||(g.copyLimit!==null&&!Number.isInteger(g.copyLimit))))throw Error('戰法持有份數格式錯誤');if(g.exclusiveGroup!==undefined&&(typeof g.exclusiveGroup!=='string'||g.exclusiveGroup.length>80))throw Error('互斥群組格式錯誤');}if(!numeric(g.level,999)||(g.level!==null&&!Number.isInteger(g.level)))throw Error('等級格式錯誤');if(kind==='general'){if(typeof g.innate!=='string'||g.innate.length>100)throw Error('自帶戰法格式錯誤');for(const key of ['cost','strength','intellect','command','speed'])if(!numeric(g[key],key==='cost'?999:99999))throw Error('數值格式錯誤：'+key);}}
if(!Array.isArray(data.team)||data.team.length!==3||data.team.some(id=>id!==null&&!data.generals.some(g=>g.id===id)))throw Error('隊伍參照錯誤');if(!Array.isArray(data.equipped)||data.equipped.length!==3||data.equipped.some(a=>!Array.isArray(a)||a.length>50||a.some(id=>!data.tactics.some(t=>t.id===id))||new Set(a).size!==a.length))throw Error('戰法參照錯誤');if(!numeric(data.cap,999)||!numeric(data.tacticCap,10)||(data.tacticCap!==null&&!Number.isInteger(data.tacticCap))||(data.duplicateRule!==undefined&&!['unknown','unique','copies'].includes(data.duplicateRule))||!['balanced','attack','sustain'].includes(data.goal)||!evidence.includes(data.ruleEvidence))throw Error('規則格式錯誤');return data;}
function analyze(s){const members=s.team.map(id=>s.generals.find(g=>g.id===id)).filter(Boolean);const errors=[],warnings=[],notes=[];const names=members.map(g=>g.name.trim());if(new Set(names).size!==names.length)errors.push('同名武將重複：請在遊戲核對可否同隊。');if(new Set(members.map(g=>g.id)).size!==members.length)errors.push('同一筆武將重複配置。');if(members.some(g=>g.region!==s.region))errors.push('隊伍包含不同地區資料，不可直接混用。');if(members.some(g=>g.season!=='S2'))warnings.push('含非 S2 資料，請核對賽季。');if(members.some(g=>!g.owned))warnings.push('含未標記擁有的武將，這是規劃參考隊。');if(members.some(g=>g.historical))warnings.push('含歷史資料（'+[...new Set(members.filter(g=>g.historical).map(g=>g.region==='TW'?'台灣':'港澳'))].join('、')+'）；機制與數值須用當前遊戲核對。');if(s.cap===null)warnings.push('統御上限未填，無法判定統御是否合法。');if(s.ruleEvidence==='unknown')warnings.push('編制規則證據尚未確認。');const costKnown=members.filter(g=>g.cost!==null),cost=costKnown.reduce((a,g)=>a+g.cost,0);if(s.cap!==null){if(cost>s.cap)errors.push('已知統御小計已超過你設定的上限。');else if(costKnown.length<members.length)warnings.push('統御缺值：小計未超限仍不能判定合法。');else notes.push('統御 '+cost+' / '+s.cap+'，符合你輸入的限制。');}
if(s.tacticCap===null)warnings.push('額外戰法格數未核對，無法判定數量限制。');s.equipped.forEach((a,i)=>{if(!s.team[i]&&a.length)errors.push('空位置仍配置戰法。');if(s.tacticCap!==null&&a.length>s.tacticCap)errors.push('位置 '+(i+1)+' 的戰法數超過設定。');a.forEach(id=>{const t=s.tactics.find(t=>t.id===id);if(t.region!==s.region)errors.push('位置 '+(i+1)+' 的戰法地區不符。');if(!t.owned)warnings.push('位置 '+(i+1)+' 含未擁有的戰法。');if(t.season!=='S2')warnings.push('位置 '+(i+1)+' 的戰法賽季須核對。');});});
const tacticUses=new Map();s.equipped.forEach((ids,i)=>{const groups=new Map();ids.forEach(id=>{const t=s.tactics.find(t=>t.id===id);const n=t.name.trim();if(!tacticUses.has(n))tacticUses.set(n,[]);tacticUses.get(n).push(t);if(t.exclusiveGroup){if(groups.has(t.exclusiveGroup))errors.push('位置 '+(i+1)+' 含相同自訂互斥群組「'+t.exclusiveGroup+'」。');groups.set(t.exclusiveGroup,true);}});});for(const [n,uses] of tacticUses){if(s.duplicateRule==='unique'&&uses.length>1)errors.push('戰法「'+n+'」重複使用，違反你設定的全隊同名唯一規則。');if(s.duplicateRule==='copies'){const limits=uses.map(t=>t.copyLimit).filter(v=>v!==null&&v!==undefined);if(!limits.length)warnings.push('戰法「'+n+'」持有份數未知，無法核對使用數。');else if(uses.length>Math.min(...limits))errors.push('戰法「'+n+'」使用 '+uses.length+' 份，超過自訂持有份數。');if(new Set(limits).size>1)warnings.push('同名戰法持有份數不一致，保守採較小值。');}if((s.duplicateRule||'unknown')==='unknown'&&uses.length>1)warnings.push('戰法「'+n+'」重複配置；同名限制未確認。');}if((s.duplicateRule||'unknown')==='unknown')warnings.push('戰法同名／份數限制未核對。');
const tags=new Set(members.flatMap(g=>g.roles).concat(s.equipped.flatMap(a=>a.flatMap(id=>s.tactics.find(t=>t.id===id).roles))));const targets={balanced:['輸出','治療','輔助'],attack:['輸出','聯動','控制'],sustain:['治療','防禦','輔助']}[s.goal];const missing=targets.filter(x=>!tags.has(x));if(members.length<3)warnings.push('隊伍尚未填滿；角色分析僅反映目前配置。');if(missing.length)notes.push('目前缺少目標角色：'+missing.join('、')+'。可從已擁有且同區資料尋找補位。');else notes.push('目標角色已覆蓋；角色標籤不能證明技能能觸發。');const stats={};for(const k of ['strength','intellect','command','speed']){const known=members.filter(g=>g[k]!==null);stats[k]={total:known.reduce((a,g)=>a+g[k],0),known:known.length,count:members.length};}const suggestions=[];return {members,errors:[...new Set(errors)],warnings:[...new Set(warnings)],notes,stats,cost,costKnown:costKnown.length,tags:[...tags],targets,missing,suggestions};}
function candidates(s,index){if(!Number.isInteger(index)||index<0||index>2)throw Error('位置錯誤');const results=s.generals.filter(g=>g.owned&&g.region===s.region&&g.season==='S2'&&!s.team.some((id,i)=>i!==index&&(id===g.id||s.generals.find(x=>x.id===id)?.name.trim()===g.name.trim()))).map(g=>{const next={...s,team:[...s.team],equipped:s.equipped.map(a=>[...a])};next.team[index]=g.id;const a=analyze(next);const costMissing=a.members.length-a.costKnown;const costStatus=s.cap===null?'unknown':a.cost>s.cap?'fail':costMissing?'unknown':'pass';return {id:g.id,name:g.name,level:g.level,historical:!!g.historical,evidence:g.evidence,current:s.team[index]===g.id,roles:g.roles,coverage:a.targets.filter(r=>a.tags.includes(r)).length,targetCount:a.targets.length,missing:a.missing,cost:a.cost,costKnown:a.costKnown,memberCount:a.members.length,costStatus,errors:a.errors,warnings:a.warnings,knownStats:a.stats,limitsStatus:a.errors.length?'fail':a.warnings.length?'unknown':'checked'};});return results.sort((a,b)=>(a.errors.length>0)-(b.errors.length>0)||b.coverage-a.coverage||(a.costStatus==='unknown')-(b.costStatus==='unknown')||a.name.localeCompare(b.name,'zh-Hant'));}
const api={candidates,initial,blank,validate,analyze,roles,evidence,validUrl};if(typeof module!=='undefined'&&module.exports)module.exports=api;root.Planner=api;
})(typeof globalThis!=='undefined'?globalThis:this);
